### PR TITLE
Add votes, and add quoting on parties that contain commas

### PR DESCRIPTION
**Pull request by HughMacdonald**
I have scraped votes from the Guardian's data set, and have added them in all but a handful (maybe 20?) of constituencies.

I have also added quotes around the party name in some constituencies, as there are a couple of parties that have commas in their name, causing the csv format to fail to line up.

### CODE REVIEW

**Comment by HughMacdonald** [comment]
As a reference, one example of a party with commas is "Beer, Baccy and Scratchings", who stood in Eastleigh

**Comment by HughMacdonald** [comment]
A quick update on this...

The following files have two independents standing against each other, with no differentiation in the .csv file as to which one is which:

blackpool-south-votes.csv
city-of-durham-votes.csv
epsom-and-ewell-votes.csv
gillingham-and-rainham-votes.csv
north-wiltshire-votes.csv
nottingham-east-votes.csv
ribble-valley-votes.csv
richmond-(yorks)-votes.csv
scunthorpe-votes.csv
sheffield,-hallam-votes.csv
south-basildon-and-east-thurrock-votes.csv
stoke-on-trent-north-votes.csv
taunton-deane-votes.csv
uxbridge-and-south-ruislip-votes.csv
wells-votes.csv
witney-votes.csv

I'm going to give them each the votes that they got, but I wanted to keep that as a separate commit so that they would be flagged separately.

**Comment by philipjohn** [comment]
This is great, thanks @HughMacdonald !

Looks like we have crossed over each other with some of these. I need to fix the Travis stuff before merging this to ensure everything is 'tickety boo'.

**Comment by HughMacdonald** [comment]
Great - glad it's all good.

If anyone wants the raw data I used, it came from here:

http://visuals.guim.co.uk/2015/05/election/data/liveresults.json

**Pull request merged**
